// Generated by gencpp from file where_am_i/DriveToTarget.msg
// DO NOT EDIT!


#ifndef WHERE_AM_I_MESSAGE_DRIVETOTARGET_H
#define WHERE_AM_I_MESSAGE_DRIVETOTARGET_H

#include <ros/service_traits.h>


#include <where_am_i/DriveToTargetRequest.h>
#include <where_am_i/DriveToTargetResponse.h>


namespace where_am_i
{

struct DriveToTarget
{

typedef DriveToTargetRequest Request;
typedef DriveToTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DriveToTarget
} // namespace where_am_i


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::where_am_i::DriveToTarget > {
  static const char* value()
  {
    return "c8652349d2a34a90a09475339e2a93d9";
  }

  static const char* value(const ::where_am_i::DriveToTarget&) { return value(); }
};

template<>
struct DataType< ::where_am_i::DriveToTarget > {
  static const char* value()
  {
    return "where_am_i/DriveToTarget";
  }

  static const char* value(const ::where_am_i::DriveToTarget&) { return value(); }
};


// service_traits::MD5Sum< ::where_am_i::DriveToTargetRequest> should match 
// service_traits::MD5Sum< ::where_am_i::DriveToTarget > 
template<>
struct MD5Sum< ::where_am_i::DriveToTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::where_am_i::DriveToTarget >::value();
  }
  static const char* value(const ::where_am_i::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::where_am_i::DriveToTargetRequest> should match 
// service_traits::DataType< ::where_am_i::DriveToTarget > 
template<>
struct DataType< ::where_am_i::DriveToTargetRequest>
{
  static const char* value()
  {
    return DataType< ::where_am_i::DriveToTarget >::value();
  }
  static const char* value(const ::where_am_i::DriveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::where_am_i::DriveToTargetResponse> should match 
// service_traits::MD5Sum< ::where_am_i::DriveToTarget > 
template<>
struct MD5Sum< ::where_am_i::DriveToTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::where_am_i::DriveToTarget >::value();
  }
  static const char* value(const ::where_am_i::DriveToTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::where_am_i::DriveToTargetResponse> should match 
// service_traits::DataType< ::where_am_i::DriveToTarget > 
template<>
struct DataType< ::where_am_i::DriveToTargetResponse>
{
  static const char* value()
  {
    return DataType< ::where_am_i::DriveToTarget >::value();
  }
  static const char* value(const ::where_am_i::DriveToTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WHERE_AM_I_MESSAGE_DRIVETOTARGET_H
